### ISSUE TITLE
Gain a working relationship with GPC

### ISSUE THREAD

**Issue by 3vivekb** [codeforsanjose/Open311SanJose#1]

**Comment by 3vivekb** [comment]
I tried.  It went really poorly.  This will probably never happen.

**Comment by howdoicomputer** [comment]
I have an in with [GPC](http://www.worldgpc.com/). Want me to give it a shot?

**Comment by 3vivekb** [comment]
I meant: http://www.graffiticalifornia.com/.  Smartass.
