### ISSUE TITLE
[App] API design

### ISSUE THREAD

**Issue by arichen** [codeforsanjose/Open311SanJose#12]
Organize a list of API call needed to our own backend. Work with @JamesHaskell .

**Comment by hassan** [comment]
Can you clarify this? What do you need that differs from the Open311 standard? (http://wiki.open311.org/GeoReport_v2/)

**Comment by arichen** [comment]
Hi @hassan, since we'll have push notifications to app for issue status updates, we will have a server handling this. E.g. fetching status from CitySourced server, and perform push notification to user.
